### ISSUE TITLE
License

### ISSUE THREAD

**Issue by ehntoo** [jonathangjertsen/SpiTransactionFramer#1]
Thanks for this extension, I'm finding it really useful! It would also make a great starting point for some other high-level analyzers I'm working on - would it be possible to get a License file in the repository to eliminate any ambiguity about license terms?

**Comment by jonathangjertsen** [comment]
Of course, thanks for reminding me. See https://github.com/jonathangjertsen/SpiTransactionFramer/blob/master/LICENSE
