### ISSUE TITLE
Export does not include framing

### ISSUE THREAD

**Issue by hawkandspit** [jonathangjertsen/SpiTransactionFramer#3]
When I export from the SPI analyzer, I get "Time [s]", "Packet ID", "MOSI", and"MISO", but not the framing Enable/Disable information.

**Comment by jonathangjertsen** [comment]
Can you provide an example .sal file? I don't have the kit I was using to develop this analyzer anymore.

**Comment by hawkandspit** [comment]
Here it is.

Jeff Thompson  |  Senior Electrical Engineer - Firmware
+1 704 752 6513 x1394
www.invue.com

***@***.***

**Comment by jonathangjertsen** [comment]
I think Github dropped the attachment, please send it to jonath.re@gmail.com

**Comment by jonathangjertsen** [comment]
Thanks for the file.

It seems that you are exporting from the underlying SPI analyzer developed by Saleae, not the SPI transaction framer high-level analyzer (HLA). The SPI transaction framer does not even have an export option. 

I don't know why Saleae's SPI analyzer doesn't export the Enable and Disable times, I suggest creating a ticket at https://ideas.saleae.com/b/feature-requests/.

I think you can still use this HLA to get the data you need. Go to the data table view and select "Export Table", with the SPI transaction framer enabled but not the SPI analyzer:

![Capture](https://user-images.githubusercontent.com/7355797/153419058-166c2fb8-4141-4afe-8149-fbc5fbd1be99.PNG)

This should result in a CSV that looks something like this:

```csv
name,type,start_time,duration,"mosi","miso"
"SPI transaction framer","SpiTransaction",0.038764704,0.001719872,0xB080CA0C00,0x004A434200
"SPI transaction framer","SpiTransaction",0.040507432,0.001702696,0xB080CC0000,0x004A434200
"SPI transaction framer","SpiTransaction",0.042233968,0.001702416,0xB080CE1700,0x004A434200
"SPI transaction framer","SpiTransaction",0.043958896,0.00170232,0xB080D01700,0x004A434200
"SPI transaction framer","SpiTransaction",0.045682376,0.001702416,0xB080D20000,0x004A434200
"SPI transaction framer","SpiTransaction",0.047406688,0.001709128,0xB080D401000014,0x004A4342000000
"SPI transaction framer","SpiTransaction",0.049136992,0.001708944,0xB080D8FE000012,0x004A4342000000
"SPI transaction framer","SpiTransaction",0.050869816,0.001709664,0xB080DC01000026,0x004A4342000000
"SPI transaction framer","SpiTransaction",0.052601272,0.00170964,0xB080E00100001F,0x004A4342000000
"SPI transaction framer","SpiTransaction",0.054334112,0.001708976,0xB080E40D000003,0x004A4342000000
"SPI transaction framer","SpiTransaction",0.056065384,0.001708936,0xB080E800D00C88,0x004A4342000000
"SPI transaction framer","SpiTransaction",0.057796104,0.001709248,0xB080EC00000021,0x004A4342000000
"SPI transaction framer","SpiTransaction",0.059527416,0.001708768,0xB080F000000014,0x004A4342000000
```

You can derive the enable and disable transitions from the start and duration. `start_time` is when the enable signal went low, `start_time + duration` is when it went high again.

**Comment by hawkandspit** [comment]
Thanks, will do!

Jeff Thompson  |  Senior Electrical Engineer - Firmware
+1 704 752 6513 x1394
www.invue.com

***@***.***
